### ISSUE TITLE
Wrong type for method DeepCopyObject

### ISSUE THREAD

**Issue by franpog859** [DexterPOSH/myplatform-operator#2]
Hey! I followed [your tutorial](https://www.techtarget.com/searchitoperations/tutorial/How-to-build-a-Kubernetes-operator) to learn how to create a Kubernetes operator but I encountered a problem. I got an error [right there](https://github.com/DexterPOSH/myplatform-operator/blob/main/controllers/inhouseapp_controller.go#L65) and I'm not sure how to fix that. I created my operator in a repo subdirectory, do you think it may be the case?

Here is the error itself:
`cannot use instance (variable of type *v1alpha1.SomeNewResource) as client.Object value in argument to r.Get: wrong type for method DeepCopyObject (have func() invalid type, want func() k8s.io/apimachinery/pkg/runtime.Object)compiler[InvalidIfaceAssign](https://pkg.go.dev/golang.org/x/tools/internal/typesinternal?utm_source%3Dgopls#InvalidIfaceAssign)`

**Comment by DexterPOSH** [comment]
Thanks for trying out the article. Did you run `make generate` to auto-generate the deep copy methods for your struct? If I recall it has to be run every time you make modifications to the struct.

**Comment by franpog859** [comment]
Ok, I think I got something wrong with my GOPATH 😅 Everything seems to be ok now. Thanks! I'm closing the issue
